### ISSUE TITLE
Capture region BEDs for validations in bioRxiv paper

### ISSUE THREAD

**Issue by chapmanb** [qiaseq/qiaseq-dna#15]
Thanks so much for making your validation datasets available as part of the bioRxiv paper on smcounter2. These are really useful and cover an important space that is currently missing from validations; tumor-only, low frequency and UMIs are common in a lot of the analyses we current run.

I've been working on putting together an automated validation with these input and have the input reads with UMIs and truth datasets prepared as fastq and VCFs:

https://github.com/bcbio/bcbio_validation_workflows#somatic-low-frequency-variants
https://github.com/bcbio/bcbio_validation_workflows/blob/master/somatic-lowfreq/smcounter2-umi.yaml

and would like to also include only validation in the target regions. Would you be able to share the target region BED files for these three test datasets:

- N13532 -- 228-gene custom panel (CDHS-13532Z-10181)
- N0261 -- Captures 269 additional indels (CDHS-13907Z-562)
- M0253 -- QIAseq Actionable Solid Tumor Panel (DHS-101Z). I found the list of genes in the panel (https://www.qiagen.com/us/shop/sample-technologies/dna/genomic-dna/qiaseq-targeted-dna-panels/?catno=DHS-101Z) but didn't find a BED file for the targets.

Apologies if I missed these somewhere and thank you again for making all this data available.

**Comment by rpadmanabhan** [comment]
Sorry i think we missed adding the target region files to our data repository. Those 3 datasets should have the appropriate target region bed files now.
https://storage.googleapis.com/smcounterv2-paper/N0261/CDHS-13907Z-562.roi.bed
https://storage.googleapis.com/smcounterv2-paper/N13532/CDHS-13532Z-10181.roi.bed
https://storage.googleapis.com/smcounterv2-paper/M0253/DHS-101Z.roi.bed

**Comment by chapmanb** [comment]
Raghavendra -- thanks so much for these BED files and for the truth data. This is a great help and I put together initial validation runs of 3 callers (VarDict, FreeBayes, Pisces) with the inputs:

https://github.com/bcbio/bcbio_validation_workflows#somatic-low-frequency-variants

Here are the initial validation results. 

https://github.com/bcbio/bcbio_validations/tree/master/somatic-lowfreq#low-frequency-umi-tagged-tumor-only-samples

These test sets are really useful for identifying low frequency difficulties and we'll be iterating trying to improve them. I'd be happy for any thoughts and feedback as you continue to work on smcounter2 and thank you again for the work.

**Comment by xuchang116** [comment]
Hi Brad, Thank you for posting the validation results. I wonder if you can share the fgbio commands and parameters you used? I am interested in how they differ from what we used. 

Also, do you plan to include smCounter2 in your validation study (using an independent dataset)?
