### ISSUE TITLE
Zero on-target reads found for read set

### ISSUE THREAD

**Issue by Tato14** [qiaseq/qiaseq-dna#20]
Hi,

First of all, thanks for the great tool! I am using smCounter1 with great results on QIAseq DNA data. I would like to use smCounter2 but I'm having some problems with the pipeline. 

I managed to solve most of my problems but I'm stuck with this one. Seems that most of me reads drop because they are not close to the SPE priming site. I am not sure where the problem could come from. Any idea?

Thanks!

[45249_S5.run_log.2018.09.20_14.53.25.txt](https://github.com/qiaseq/qiaseq-dna/files/2401528/45249_S5.run_log.2018.09.20_14.53.25.txt)
[45249_S5.umi_filter.summary.txt](https://github.com/qiaseq/qiaseq-dna/files/2401529/45249_S5.umi_filter.summary.txt)
[45249_S5.umi_filter.detail.summary.txt](https://github.com/qiaseq/qiaseq-dna/files/2401530/45249_S5.umi_filter.detail.summary.txt)

**Comment by Tato14** [comment]
Hi @rpadmanabhan. Guess I was using the wrong file. Seems that I had the same problem with simple repeats and rmsk (formating errors). Where could I find the files that you used?
Thanks!

**Comment by Tato14** [comment]
Hi @rpadmanabhan. It seems that I am having problems with the bed files. I am having also problems now with the roi.bed (attached) and I guess I would have problems with the simple repeats and rmsk. Where could I check the file format of them? Thanks

[45249_S5.run_log.2018.09.21_09.45.50.txt](https://github.com/qiaseq/qiaseq-dna/files/2404421/45249_S5.run_log.2018.09.21_09.45.50.txt)

[QIAseq_DNA_panel.CDHS-13593Z-900.roi.bed.zip](https://github.com/qiaseq/qiaseq-dna/files/2404426/QIAseq_DNA_panel.CDHS-13593Z-900.roi.bed.zip)

**Comment by rpadmanabhan** [comment]
Yes, the repeat files are different in smCounter2, you can get them from here : 

--repBed : [](https://storage.googleapis.com/qiaseq-dna/data/annotation/simpleRepeat.full.bed)
--srBed : [](https://storage.googleapis.com/qiaseq-dna/data/annotation/SR_LC_SL.full.bed)

The roi file for your catalog panel : 
[CDHS-13593Z-900.roi.txt](https://github.com/qiaseq/qiaseq-dna/files/2405163/CDHS-13593Z-900.roi.txt)

 * Github would not let me upload a .bed file here  so i renamed it with a .txt extension, feel free to change it back to .bed

**Comment by Tato14** [comment]
Hi @rpadmanabhan, I assume that you attached links after --repBed and --srBed? I cannot see them. Thanks

**Comment by Tato14** [comment]
> Hi @rpadmanabhan, should I assume that you attached links after --repBed and --srBed? I cannot see them. Thanks

Fund them here: https://github.com/qiaseq/qiaseq-smcounter-v2/issues/4#issuecomment-398058707

**Comment by Tato14** [comment]
Hi @rpadmanabhan,

Now I'm not sure what the error claims. Is it a path problem?

Thanks!
[45249_S5.run_log.2018.09.21_16.14.11.txt](https://github.com/qiaseq/qiaseq-dna/files/2413993/45249_S5.run_log.2018.09.21_16.14.11.txt)

**Comment by rpadmanabhan** [comment]
Hey , Looks like the Rscript calculating the p-values during variant calling failed. Could you check the other log , i.e. run.log to see what the error message was ? Also could you check the intermediate/ folder to see if you got variant calls.

**Comment by Tato14** [comment]
Hi @rpadmanabhan, 
The error still persists with the update. I checked the intermediate folder and I found the input files bkg.45249_S5.txt and the nopval.45249_S5.VariantList.long.txt files but no the output ones (45249_S5.VariantList.long.txt and 45249_S5.umi_depths.lod.bedgraph). However, I was not able to find the "other log" that you mention before. 


[45249_S5.run_log.2018.09.26_09.48.16.txt](https://github.com/qiaseq/qiaseq-dna/files/2418776/45249_S5.run_log.2018.09.26_09.48.16.txt)

**Comment by rpadmanabhan** [comment]
Could you tell me the exact command you used to run the pipeline ?

**Comment by Tato14** [comment]
python run_qiaseq_dna.py run_sm_counter_v2.params.txt v2 single 45249_S5

I also attached the run_sm_counter_v2.params.txt file
[run_sm_counter_v2.params.txt](https://github.com/qiaseq/qiaseq-dna/files/2419664/run_sm_counter_v2.params.txt)

**Comment by rpadmanabhan** [comment]
Okay, did you get the exception/error from the Rscript to your screen ? If so, could you post it , just need to figure out why the script failed.

**Comment by Tato14** [comment]
Hi @rpadmanabhan. Don't know what happened but everything seems to work now. Thank you for your help!
