### ISSUE TITLE
Problems detecting ASXL1 c.1934dupG; p.(Gly646TrpfsTer12) / chr20:31022441

### ISSUE THREAD

**Issue by Tato14** [qiaseq/qiaseq-dna#24]
Hi!

I am having trouble detecting this mutation in a set of samples since we switch to smCounter_v2 (QIAseq-DNA-smCounter2.57233_S5.smCounter.anno.txt). However, this mutation is clearly detected (AF ~ 30%) in the smCounter_v1 (QIAseq-DNA-smCounter_v.1.57233_S5.smCounter.anno.txt). 

Interestingly, another sample of the same patient (57441_S12) detects the mutation in smCounter_v2. 

Does it have something to do with the repetitive region files?

Thanks!

[QIAseq-DNA-smCounter2.57441_S12.smCounter.anno.txt](https://github.com/qiaseq/qiaseq-dna/files/2782369/QIAseq-DNA-smCounter2.57441_S12.smCounter.anno.txt)
[QIAseq-DNA-smCounter2.57233_S5.smCounter.anno.txt](https://github.com/qiaseq/qiaseq-dna/files/2782370/QIAseq-DNA-smCounter2.57233_S5.smCounter.anno.txt)
[QIAseq-DNA-smCounter_v.1.57233_S5.smCounter.anno.txt](https://github.com/qiaseq/qiaseq-dna/files/2782371/QIAseq-DNA-smCounter_v.1.57233_S5.smCounter.anno.txt)

**Comment by j-dicarlo** [comment]
If you post your BAM files and intermediate qiaseq output text files somewhere we can download them, we will take a look at the root cause.  Thanks.

**Comment by Tato14** [comment]
Hi!
I uploaded all the files to a Google Drive (https://drive.google.com/file/d/1NQ0PSTmcmYmGMPOLO-UDqORdFZAmIa_a/view?usp=sharing)

Please, let me know if you need anything else.
Thanks!

**Comment by j-dicarlo** [comment]
V2 of smCounter has an improved homopolymer filter that makes use of the UMI.   The ASXL1 variant looks real, but the homopolymer filter will not pass this type of variant unless the read set has at depth of at least 1.8 reads per UMI.  Probably the S12 read set is just above this threshold, and the S5 read set is just below the threshold.  In general, you need to sequence to depth of at least 3 to 5 to reads per UMI (or whatever the handbooks says) to obtain good sensitivity and specificity.
