### ISSUE TITLE
error on module edlib

### ISSUE THREAD

**Issue by bioinfo-dirty-jobs** [qiaseq/qiaseq-dna#25]
I download the  github and I build the docker image from Dockerfile. I download the last repositoryas suggest on the README.
```
:/srv/qgen/code/qiaseq-dna# git pull
Already up-to-date.

```
I have this error:
```
root@9090c2ea675e:/srv/qgen/code/qiaseq-dna# python /srv/qgen/code/qiaseq-dna/run_qiaseq_dna.py run_sm_counter_v2.params.txt v1 single NEB_S2 
Traceback (most recent call last):
  File "/srv/qgen/code/qiaseq-dna/run_qiaseq_dna.py", line 8, in <module>
    import core.prep
  File "/srv/qgen/code/qiaseq-dna/core/prep.py", line 10, in <module>
    import primer_trim
  File "/srv/qgen/code/qiaseq-dna/core/primer_trim.py", line 6, in <module>
    import edlib
ImportError: No module named edlib

```

**Comment by rpadmanabhan** [comment]
Sorry about that , looks like I have not updated the Dockerfile after the last change I made. I need to add a couple of things there. For now, you could use : rpadmanabhan9/qiaseq-dna:pipeline , I will update the Dockerfile in a day or two.

**Comment by bioinfo-dirty-jobs** [comment]
Thanks so much!!! I resolve change the docker File.

**Comment by rpadmanabhan** [comment]
I updated the Dockerfile on the master branch , could try to build the image again and run the example. Thanks.
