### ISSUE TITLE
Error while running the tests: KeyError: read fragments per MT, mean

### ISSUE THREAD

**Issue by danablanc** [qiaseq/qiaseq-dna#27]
Hello,

I tried to run your tests while using the Docker image.
However I got the following error:

/srv/qgen/code/qiaseq-dna# python tests/simulate_tests.py True;
Starting to run tests.......
------------------
Running sm_counter pipeline

Traceback (most recent call last):
  File "tests/simulate_tests.py", line 35, in <module>
    test_sm_counter.validate_umi_read_frags_metrics("NEB_S2.umi_frags.summary.txt")
  File "/srv/qgen/code/qiaseq-dna/tests/test_sm_counter.py", line 57, in validate_umi_read_frags_metrics
    assert utils.compare_with_tolerance(metrics["read fragments per MT, mean"],READS_PER_MT,0.02) is True
**KeyError: 'read fragments per MT, mean'**

**The content of NEB_S2.umi_frags.summary.txt:**
434871	UMIs
3399799	read fragments
7.8	read fragments per UMI, mean
2	read fragments per UMI, 25th percentile
6	read fragments per UMI, 50th percentile
12	read fragments per UMI, 75th percentile
120	sample fragment length, 25th percentile (bp)
171	sample fragment length, 50th percentile (bp)
238	sample fragment length, 75th percentile (bp)
35.1	% of UMIs with >= one read from internal downstream priming
21.9	% of reads from internal downstream priming

I'll appreciate your help finding the problem. Thank you.

**Comment by rpadmanabhan** [comment]
Thanks for reporting this, looks like that metric name was not updated in the test script. I have done so now, and it passes for me locally, you can clone the master branch again and try.

#28

**Comment by danablanc** [comment]
Thank you! Seems that the problem was fixed
