### ISSUE TITLE
Running gsutil -m cp -r gs://qiaseq-dna/data ./

### ISSUE THREAD

**Issue by GAgafencu** [qiaseq/qiaseq-dna#32]
When I try to run: gsutil -m cp -r gs://qiaseq-dna/data ./
I get the following message: ServiceException: 401 Anonymous caller does not have storage.objects.get access to qiaseq-dna/data.
CommandException: 1 file/object could not be transferred.

What would be the solution for this issue?

**Comment by rpadmanabhan** [comment]
Looks like some files were still private , I changed them, could you try again ?
Thanks

**Comment by GAgafencu** [comment]
Dear Sir,

I still can not download the data. I get the same error message.

Best wishes,
Grigore-Aristide Gafencu
DPhil Student

MRC Molecular Haematology Unit
Weatherall Institute of Molecular Medicine, John Radcliffe Hospital
University of Oxford, Oxford, UK
Tel: 0185222410

**Comment by rpadmanabhan** [comment]
Sorry about that, I think it should be accessible now, I was able to as a an anonymous user on my local machine.

**Comment by GAgafencu** [comment]
It worked.Thanks for your help!
