### ISSUE TITLE
missing module qiaseq-smcounter-v2.run

### ISSUE THREAD

**Issue by Blowfish82** [qiaseq/qiaseq-dna#36]
### Hi,
I was trying to run the test data exactly like in the example code in qiaseq/qiaseq-dna.
When I ran:  
python    /srv/qgen/code/run_qiaseq_dna.py   run_sm_counter_v2.params.txt    v2   single  NEB_S2 > run.log 2>&1 &  
I got an error message in the run.log:

```
Traceback (most recent call last):
  File "/srv/qgen/code/run_qiaseq_dna.py", line 16, in <module>
    import core.sm_counter_wrapper
  File "/srv/qgen/code/core/sm_counter_wrapper.py", line 7, in <module>
    sm_counter_v2 = __import__("qiaseq-smcounter-v2.run")
ImportError: No module named qiaseq-smcounter-v2.run
```
-------------------------------------------------------------------------------

Do I miss something? I´m pretty noob in phyton.
Thank you for any help!

**Comment by rpadmanabhan** [comment]
Maybe you missed the `--recursive` flag during the git clone ?

**Comment by Blowfish82** [comment]
Hello, thanks for you answer.
But I also could´t find this file “qiaseq-smcounter-v2.run ” in the git qiaseq/qiaseq-dna repository manually.


Von: Raghavendra Padmanabhan <notifications@github.com>
Gesendet: Montag, 6. Mai 2019 15:26
An: qiaseq/qiaseq-dna <qiaseq-dna@noreply.github.com>
Cc: Willscher, Edith <Edith.Willscher@uk-halle.de>; Author <author@noreply.github.com>
Betreff: Re: [qiaseq/qiaseq-dna] missing module qiaseq-smcounter-v2.run (#36)


Maybe you missed the --recursive flag during the git clone ?

**Comment by rpadmanabhan** [comment]
qiaseq-smcounter-v2 is a submodule of this repository, you need to add the recursive flag to your git clone. If you missed it during the clone you can do ```git submodule init``` and ```git submodule update```

**Comment by Blowfish82** [comment]
Thank you, that solved it. Indeed two subfolders were empty.
