### ISSUE TITLE
run erro

### ISSUE THREAD

**Issue by fanyucai1** [qiaseq/qiaseq-dna#37]
Hi my Dockerfile like this:
#################################
FROM qiaseq/qiaseq-dna:latest
USER root
RUN cd /srv/qgen/code/ && git clone --recursive https://github.com/qiaseq/qiaseq-dna.git && chmod 777 -R qiaseq-dna/
COPY DHS-3501Z.primer3.txt /srv/qgen/example/
COPY DHS-3501Z.roi.bed /srv/qgen/example/
ENV PATH /srv/qgen/code/qiaseq-dna/:$PATH
WORKDIR /srv/qgen/example/
###################################

I  build a new docker and run command as follows:
docker run -i -v /software/qiaseq-dna/data/:/srv/qgen/data/ -v /data/Panel275/test/:/srv/qgen/example/ qiaseq-dna:1.0 python /srv/qgen/code/qiaseq-dna/
run_qiaseq_dna.py run_sm_counter_v2.params.txt v2 single MP190004F

################################## run_sm_counter_v2.params.txt  as follows:
[MP190004F]
readFile1 = /srv/qgen/example/MP190004F_L1_1.fq
readFile2 = /srv/qgen/example/MP190004F_L1_2.fq
instrument = Other
primerFile = /srv/qgen/example/DHS-3501Z.primer3.txt
roiBedFile = /srv/qgen/example/DHS-3501Z.roi.bed
platform = Illumina
runCNV = False
sampleType =  Single
duplex = False
######################################my erro message:
2019-05-08 05:12:36.641 prep: done
2019-05-08 05:12:36.641 align: starting read alignment
2019-05-08 05:19:18.371 align: done aligning reads to genome, bam file: MP190004F.align.bam
2019-05-08 05:19:18.371 umi_filter: starting...
2019-05-08 05:19:18.399 ('# of primers:', 11311)
2019-05-08 05:25:06.012 Traceback (most recent call last):
2019-05-08 05:25:06.013   File "/srv/qgen/code/qiaseq-dna/run_qiaseq_dna.py", line 203, in <module>
2019-05-08 05:25:06.013 run((readSet,paramFile,vc),tumorNormal = False)
2019-05-08 05:25:06.013   File "/srv/qgen/code/qiaseq-dna/run_qiaseq_dna.py", line 57, in run
2019-05-08 05:25:06.013 core.umi_filter.run(cfg, bamFileIn)
2019-05-08 05:25:06.013   File "/srv/qgen/code/qiaseq-dna/core/umi_filter.py", line 380, in run
2019-05-08 05:25:06.013 raise UserWarning("< 5 percent or < 50 on-target read fragments found for read set: {}".format(readSet))
2019-05-08 05:25:06.013 UserWarning
2019-05-08 05:25:06.013 :
2019-05-08 05:25:06.013 < 5 percent or < 50 on-target read fragments found for read set: MP190004F
###################################
 what should I do?
can you help me?
Thanks.

**Comment by rpadmanabhan** [comment]
That error usually occurs when the wrong catalog ID (primer and roi files) are used , you can verify that by grepping for the primer sequences in the fastq to see if you get some matches.
 
Less likely, but it could also be that your reads are indeed pretty bad leading to too many off-targets.

**Comment by fanyucai1** [comment]
my primer file like this:
<img width="749" alt="屏幕快照 2019-05-09 上午9 29 48" src="https://user-images.githubusercontent.com/20902090/57421229-78fe1600-723d-11e9-8745-48b0c1db4e62.png">

#######################
I run the command :grep "GGAGTTCATCCTGCTAGCTGGGTTC" MP190004F.prep.R1.fastq
<img width="1463" alt="屏幕快照 2019-05-09 上午9 30 42" src="https://user-images.githubusercontent.com/20902090/57421247-9206c700-723d-11e9-93dd-49ba39371c89.png">

**Comment by fanyucai1** [comment]
But my raw data  was short by run trim, and get the ***.prep.R1.fastq file, I think this process the common sequence should be trimmed, but in my data still retain.

**Comment by rpadmanabhan** [comment]
The trimmer looks for the custom sequencing adapter AATGTACAGTA.. in the first ~ 20000 reads and if >95% of them have it , then this oligo is trimmed in all the reads. Maybe the first ~ 20000 reads failed this for your case ? Could you verify this from the log file (the MP190004F.run_log* file) ?
If that is the case, I suggest doing this :

modify the file core/prep.py at this line by adding an additional flag : 
https://github.com/qiaseq/qiaseq-dna/blob/master/core/prep.py#L26
``` python
"--tagname-primer-error {pe} --tagname-umi {mi} --trim-custom-seq-adapter "
```
This will force the program to look for the custom sequencing adapter in all the reads.

**Comment by rpadmanabhan** [comment]
Or if you find it easier, you could just trim the custom sequencing adapter using cutadapt or something and give that fastq as input to the pipeline.

**Comment by rpadmanabhan** [comment]
There was a bug introduced in the trimming code which was causing it not to trim the custom sequencing adapter even when present. Please pull the code again and try, it should work now. Sorry for the inconvenience.
