### ISSUE TITLE
Inconsistent truth results in the smCounter2 paper between the Bioinformatics version and the Biorxiv version

### ISSUE THREAD

**Issue by haodongchen** [qiaseq/qiaseq-dna#38]
I compared the truth results in the Supplementary data of the Bioinformatics paper and the Biorxiv version and found that the Biorxiv version has more mutations than the Bioinformatics paper. Here are what I found:

N13532 and N0261: 4	88536013	.	TAGCAGTGACAGCAGCAAC	T
N0015: 11	18852328	rs142948111	ATGCTTATT	A
N11582: 1	100366446	rs35956186	GTT	G

Which version is the correct one?

**Comment by xuchang116** [comment]
Thanks for pointing out the inconsistencies! Please use the ground truth files in the Bioinformatics paper. The variants you mentioned partially but not fully overlap with the target regions, so they were not included in the final paper.

**Comment by haodongchen** [comment]
Hi Chang, 

Thank you for your reply. I have another follow-up question. In the truth file of bty790_M0253.HDx.Q7.vcf, there is one mutation located in the gene MET at chr7:116423428
chr7	 116423428	.	T	G

However, in the bed file of DHS-101Z.roi.bed, the two regions covering MET gene do not cover this mutation:
chr7	116423396	116423418	MET
chr7	116423463	116423485	MET

So how was this mutation called if it was not in the bed regions?

**Comment by xuchang116** [comment]
Hi Haodong, 

They are in the bed file we used (attached here). You may got a wrong bed file. 

[DHS-101Z.primer3.roi.bed.txt](https://github.com/qiaseq/qiaseq-dna/files/3163915/DHS-101Z.primer3.roi.bed.txt)

Chang

**Comment by haodongchen** [comment]
Hi Chang,

Thank you for giving me the correct bed file. I downloaded the bed file from the following two links, although they are actually the same file:

https://storage.googleapis.com/smcounterv2-paper/M0253/DHS-101Z.roi.bed
https://storage.googleapis.com/qiaseq-dna/example/DHS-101Z.roi.bed

Would you mind uploading the correct bed files for N0015, N0030, N0261 and N13532?

Greatly appreciate!
Haodong

**Comment by rpadmanabhan** [comment]
Sorry for the confusion, We re-uploaded the correct M0253 target bed file used in the paper. The N0015 and N0030 bed files have also been uploaded. Please refer to the updated URLs here : https://github.com/qiaseq/smcounter-v2-paper

https://github.com/qiaseq/smcounter-v2-paper/issues/2

**Comment by haodongchen** [comment]
Thank you both for answering my questions!
