### ISSUE TITLE
compare result

### ISSUE THREAD

**Issue by fanyucai1** [qiaseq/qiaseq-dna#39]
hi, I want to compare the smcounter2 with VarDict.

But I want input bam file, I run the normal sample and tumor sample in single model.

there are two bam files.
<img width="527" alt="屏幕快照 2019-05-20 下午5 07 32" src="https://user-images.githubusercontent.com/20902090/58009861-e6555500-7b21-11e9-910d-d2aec5b8eb27.png">

My question is:
which bam file could be used?
2019NC.align.bam or 2019NC.bam

And there is a parameter '-F' in VarDict, whether or not this parameter should be used?

Thanks.

**Comment by rpadmanabhan** [comment]
The 2019NC.bam is used for variant calling. It is a filtered version of the *.align.bam.
Sorry, I have no suggestions for the VarDict param, I have not used it in a long time to know the details well.
