### ISSUE TITLE
CDHS-13627Z-237.primer3.txt file

### ISSUE THREAD

**Issue by Tato14** [qiaseq/qiaseq-dna#40]
Hi! I want to run smCounter2 on this panel. I already have the bed file (QIAseq_DNA_panel.CDHS-13627Z-237.roi.bed) but I cannot find the primer3 file. Could you please send it to me? Thanks!

**Comment by rpadmanabhan** [comment]
[CDHS-13627Z-237.primer3.txt](https://github.com/qiaseq/qiaseq-dna/files/3208308/CDHS-13627Z-237.primer3.txt)
Please find it attached here.
