### ISSUE TITLE
ctDNA parameter

### ISSUE THREAD

**Issue by fanyucai1** [qiaseq/qiaseq-dna#41]
hi doctor:

I run qiaseq-dna, with normal and tumor samples.  But I do not know tumorPurity ?what should I do? And I want to get more variable sites, which parameters in config should I can changed?

Otherwise, i run tumor and normal samples compare the vardict in ctDNA, there are many sites will be lost.   Are there some parameters to get more sites?

**Comment by xuchang116** [comment]
Hi fanyucai1, can you send me (chang.xu@qiagen.com) the VarDict and smCounter2 results (VCFs) of your tumor-normal samples?

**Comment by xuchang116** [comment]
Hi fanyucai1, VarDict reported 357,073 variants, which is unlikely for QIAseq panels. My suggestion is to try different parameter values with VarDict for a reasonable number of variants.
