### ISSUE TITLE
CDHS-14434Z-389 bed file

### ISSUE THREAD

**Issue by Tato14** [qiaseq/qiaseq-dna#42]
Hi!

Sorry for the spam again. Could I get the bed files for this panel?

In addtition, is there any place where I could check all this bed files?

Thanks!

**Comment by rpadmanabhan** [comment]
[CDHS-14434Z-389.roi.txt](https://github.com/qiaseq/qiaseq-dna/files/3330764/CDHS-14434Z-389.roi.txt)
[CDHS-14434Z-389.primer3.txt](https://github.com/qiaseq/qiaseq-dna/files/3330765/CDHS-14434Z-389.primer3.txt)

Please find the files attached. The roi has a .txt extension (github wont let me use a .bed).
You could try asking your QIAGEN sales rep about all the bed files. I am not sure how the sharing would work with a customer and what files we are allowed to share.
